deployment:
  tasks:
    - export REPO="/home/ignat016/repositories/dream-v-doma/dream-v-doma"
    - export TARGET="/home/ignat016/dream-v-doma"

    # створити папку призначення
    - /bin/mkdir -p "$TARGET"

    # синхронізація коду з ВНУТРІШНЬОЇ папки репозиторію
    - /bin/rsync -a --delete \
        --exclude='/.git' \
        --exclude='/.cpanel.yml' \
        --exclude='/node_modules' \
        --exclude='/vendor' \
        --exclude='/storage/app/*' \
        --exclude='/storage/logs/*' \
        "$REPO"/ "$TARGET"/

    # laravel-команди
    - cd "$TARGET"
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan key:generate --force || true
    - php artisan migrate --force
    - php artisan storage:link || true
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - /bin/chmod -R 775 storage bootstrap/cache
