deployment:
  tasks:
    - export SRC="/home/ignat016/repositories/dream-v-doma/dream-v-doma"
    - export TARGET="/home/ignat016/dream-v-doma"
    - export PUBLIC="/home/ignat016/public_html"

    - /bin/mkdir -p "$TARGET" "$PUBLIC"

    - /bin/rsync -a --delete \
        --exclude='/.git' \
        --exclude='/.cpanel.yml' \
        --exclude='/node_modules' \
        --exclude='/vendor' \
        --exclude='/storage/app/*' \
        --exclude='/storage/logs/*' \
        "$SRC"/ "$TARGET"/

    - cd "$TARGET"
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader || /usr/bin/composer install --no-dev --optimize-autoloader || true
    - php artisan key:generate --force || true
    - php artisan storage:link || true
    - php artisan config:cache || true
    - php artisan route:cache  || true
    - php artisan view:cache   || true
    - /bin/chmod -R 775 storage bootstrap/cache || true

    - /bin/rsync -a --delete "$TARGET/public/" "$PUBLIC/"
